import type { Metadata } from "next";
import "../ui/styles/globals.css";
import Navbar from "@/ui/components/modules/Navbar";
import { Inter, Rubik, Source_Sans_3 } from 'next/font/google';
import { open_sans, rubik } from "@/ui/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${open_sans.variable} bg-kick-gray  w-full `}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
